logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.inditex.prices: DEBUG

spring:
  application:
    name: prices
  datasource:
    url: jdbc:h2:mem:prices-db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true
